# Generated by Django 4.2.5 on 2023-12-14 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arduinoonline_delete_arduinostatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArduinoOnline',
        ),
    ]
