# Generated by Django 5.0.1 on 2024-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_arduinoonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('urls', models.TextField()),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('browser_name', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
            ],
        ),
    ]
