# Generated by Django 5.2.4 on 2025-07-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marquee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalMessage',
            new_name='MarqueeMessage',
        ),
    ]
