# Generated by Django 5.2.4 on 2025-07-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquee', '0002_rename_globalmessage_marqueemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignOffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignOnMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
