# Generated by Django 5.2.4 on 2025-07-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marquee', '0003_signoffmessage_signonmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_message', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
